project: 
  type: book 
  render: 
    - "*.qmd"
    - "!devel/"
book:
  title: "Mappeeksamen"
  subtitle: "IDR4000 - Kvantitativ metode og statistikk"
  author: "Kandidatnummer: 528. Antall ord: 12130"
  date: "22. november 2024"
  chapters:
  - index.qmd
  - 01-reliabilitet.qmd
  - 02-predikere-data.qmd
  - 03-statistiske-modeller.qmd 
  - 04-studiedesign.qmd
  - 05-gjentatte-målinger.qmd
  - 06-filosofi.qmd
  - 07-labrapport.qmd
  - kilder.qmd 
bibliography: 
 - resources/references.bib
 - resources/ref2bib.bib
csl: resources/citation-style.csl
format:
  html:
    theme: cosmo 
  pdf: 
    documentclass: scrreprt
crossref: 
  fig-title: "Figur"
  tbl-title: "Tabell"